version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["dependencies"]
    commit-message:
      prefix: "chore"
      include: "scope"
       dev-dependencies:
          patterns:
            - "@typescript-eslint/*"
            - "eslint"