on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    types: [ opened, synchronize, reopened ]

name: Canary Release

permissions:
  contents: read # to fetch code (actions/checkout)
  packages: write # to publish packages (npm publish)

jobs:
  test:
    environment: canary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun test
      - run: bun run lint
      - run: bun --bun run build
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm version prerelease --preid=canary --no-git-tag-version
      - run: npm publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
