name: Main Branch Checks

permissions:
  contents: read
  packages: read

on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test lib
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun install
    - run: bun run test
    - run: bun run build
