name: Main Branch Checks

permissions:
  contents: read
  packages: read

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun
      - uses: ./.github/actions/build
      - run: bun test
      - run: bun run lint
