on:
  push:
    branches:
      - main
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]

name: ci

permissions:
  contents: write # to fetch code (actions/checkout)
  pull-requests: write # to create release PR (google-github-actions/release-please-action)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          release-type: node
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun test
      - run: bun run lint
      - run: bun --bun run build
