on:
  pull_request:
    branches: [ main ]
    types: [ assigned, opened, synchronize, reopened ]

name: Pull Request

permissions:
  contents: read # to fetch code (actions/checkout)
  packages: write # to publish packages (npm publish) 

jobs:
  setup: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-bun
      - run: bun test
      - run: bun run lint
      - run: bun --bun run build

  canary-release: 
    runs-on: ubuntu-latest
    environment: canary
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
      - uses: actions/cache@v3
        with:
          key: dependencies
          path: |
            ./node_modules/**
            ./dist/**
      - run: npm version prerelease --preid=canary --no-git-tag-version
      - run: npm publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
