on:
  pull_request:
    branches: [main]
    types: [assigned, opened, synchronize, reopened, labeled]

name: Pull Request

permissions:
  contents: read # to fetch code (actions/checkout)
  packages: write # to publish packages (npm publish)

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-bun
      - run: bun --bun run build
      - run: bun test
      - run: bun run lint
      - name: Store build cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-${{ hashFiles('./dist/**') }}
          path: |
            ./dist/**

  canary-release:
    runs-on: ubuntu-latest
    environment: canary
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-bun
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-${{ hashFiles('./dist/**') }}
          path: |
            ./dist/**
      - run: npm version prerelease --preid=canary.$(git rev-parse --short HEAD) --no-git-tag-version
      - run: npm publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
